spring.application.name=auth-service
spring.config.import=optional:configserver:http://localhost:8888
spring.profiles.active=dev
spring.servlet.multipart.max-file-size=50MB
springdoc.default-consumes-media-type= application/json
spring.mail.host: localhost
spring.mail.port: 1025
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.auth=true
spring.mail.properties.mail.smtp.trust="*"
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.starttls.enable=true
spring.mail.properties.mail.connectiontimout=5000
spring.mail.properties.mail.timeout=3000
spring.mail.properties.mail.writetimout=5000



