spring.application.name=auth-service
spring.config.import=optional:configserver:http://localhost:8888
spring.profiles.active=dev
spring.servlet.multipart.max-file-size=50MB
springdoc.default-consumes-media-type= application/json
# Mail Configuration for Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=khchimmadi.moemen@gmail.com
spring.mail.password=yxwiklzzubuqziwz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# For local testing with MailDev, comment out Gmail config above and uncomment these:
# spring.mail.host=localhost
# spring.mail.port=1025
# spring.mail.properties.mail.smtp.auth=false
# spring.mail.properties.mail.smtp.starttls.enable=false


