export enum FormInputType {
  TEXTFIELD = 'TEXTFIELD',
  PHONE_NUMBER= 'PHONE_NUMBER',
  CHECKBOX = 'CHECKBOX',
  RADIO_BUTTON='RADIO_BUTTON',
  SELECT_BOX='SELECT_BOX',
  EMAIL='EMAIL',
  TITLE='TITLE'
}
