# Eureka configuration
eureka.client.register-with-eureka=false
eureka.instance.hostname=localhost

# Server configuration
server.port=8222

# Spring application configuration
spring.application.name=api-gateway

# Spring Cloud Gateway configuration
# Global CORS configuration
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

# Discovery locator
spring.cloud.gateway.discovery.locator.enabled=true

# Gateway routes
spring.cloud.gateway.routes[0].id=form-service
spring.cloud.gateway.routes[0].uri=lb://form-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/form-service/**

spring.cloud.gateway.routes[1].id=workflows
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/workflow/**

spring.cloud.gateway.routes[2].id=form-inputs
spring.cloud.gateway.routes[2].uri=http://localhost:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/form-inputs/**

spring.cloud.gateway.routes[3].id=form-layouts
spring.cloud.gateway.routes[3].uri=http://localhost:8081
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/form-layouts/**

spring.cloud.gateway.routes[4].id=form-templates
spring.cloud.gateway.routes[4].uri=http://localhost:8081
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/form-templates/**

spring.cloud.gateway.routes[5].id=form-multiple-values
spring.cloud.gateway.routes[5].uri=http://localhost:8081
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/multiple-values/**

# Management configuration
management.tracing.sampling.probability=1.0