# Eureka configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost


# Server configuration
server.port=8222

# Spring application configuration
spring.application.name=api-gateway

#CORS configuration
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:4200
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true Spring Cloud Gateway configuration
# Global
spring.cloud.gateway.observability.enabled=false

# Discovery locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Gateway routes

spring.cloud.gateway.routes[0].id=form-service
spring.cloud.gateway.routes[0].uri=lb://form-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/form-service/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/form-service/(?<remaining>.*), /$\{remaining}

spring.cloud.gateway.routes[1].id=workflow-service
spring.cloud.gateway.routes[1].uri=lb://workflow-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/workflow-service/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/workflow-service/(?<remaining>.*), /$\{remaining}

spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=lb://auth-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/auth-service/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/auth-service/(?<remaining>.*), /$\{remaining}

spring.cloud.gateway.httpclient.connect-timeout=5000
spring.cloud.gateway.httpclient.response-timeout=5000


# Configure retry filter
spring.cloud.gateway.routes[0].filters[0].name=Retry
spring.cloud.gateway.routes[0].filters[0].args.retries=3
spring.cloud.gateway.routes[0].filters[0].args.statuses=SERVICE_UNAVAILABLE
spring.cloud.gateway.routes[0].filters[0].args.methods=GET,POST
spring.cloud.gateway.routes[0].filters[0].args.backoff.firstBackoff=50ms
spring.cloud.gateway.routes[0].filters[0].args.backoff.maxBackoff=500ms
spring.cloud.gateway.routes[0].filters[0].args.backoff.factor=2
spring.cloud.gateway.routes[0].filters[0].args.backoff.basedOnPreviousValue=false



# Management configuration
management.tracing.sampling.probability=1.0

###############################################################################
#Logging
###############################################################################
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.http.server.reactive=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]