spring.application.name=auth-service
server.port=0
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=momo
spring.datasource.password=xpress11
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=10
# Reduce JPA startup time
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.username=postgres
#spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone= http://localhost:8761/eureka
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
application.config.workflows-url= http://localhost:8222/workflow-service
spring.zipkin.base-url=http://zipkin:9411
# Faster client-side registration
eureka.client.initialInstanceInfoReplicationIntervalSeconds=0
eureka.client.instanceInfoReplicationIntervalSeconds=5
eureka.client.registryFetchIntervalSeconds=3

# Eager initialization to speed up registration
eureka.client.eagerInitialRegistration=true

# Faster instance availability status
eureka.instance.initial-status=UP

