spring.application.name=workflow-service
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/workflow_db
spring.datasource.username=momo
spring.datasource.password=xpress11
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Camunda configuration
camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin
camunda.bpm.default-serialization-format=application/json
camunda.bpm.rest.enabled=true
camunda.bpm.webapp.enabled=true
camunda.bpm.database.type=postgres
camunda.bpm.database.schema-update=true
camunda.bpm.webapp.index-redirect-enabled=true
camunda.bpm.deployment-resource-pattern=classpath*:/processes/*.bpmn
camunda.bpm.history-level=full
camunda.bpm.job-execution.enabled=true
camunda.bpm.job-executor.wait-time-in-millis=60000  # Wait 60 seconds before processing jobs
camunda.bpm.auto-deployment-enabled=true
camunda.bpm.metrics.enabled=false
camunda.bpm.telemetry.enabled=false
camunda.bpm.run.auth.enabled=false

# Eureka configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
application.config.forms-url=http://localhost:8082/api/form-submissions