eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: forms
          uri: http://localhost:8081
          predicates:
            - Path=/api/form-submissions/**
        - id: workflows
          uri: http://localhost:8082
          predicates:
            - Path=/api/workflow/**
  config:
    import: optional:configserver:http://localhost:8888